<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PrincipioActivo;

class PrincipioActivoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $datos=[
            ['descripcion' => 'Loratadina'],
            ['descripcion' => 'Difenhidramina'],
            ['descripcion' => 'Clorfeniramina'],
            ['descripcion' => 'Cetirizina'],
            ['descripcion' => 'Fexofenadina'],
            ['descripcion' => 'Doxilamina'],
            ['descripcion' => 'Bromexhina'],
            ['descripcion' => 'Guaifenesina o'],
            ['descripcion' => 'Guayacolato de glicerilo'],
            ['descripcion' => 'Ambroxol '],
            ['descripcion' => 'Dextrometorfano '],
            ['descripcion' => 'Carboxicisteína'],
            ['descripcion' => 'Solución salina '],
            ['descripcion' => 'Nafazolina clorhidrato '],
            ['descripcion' => 'Oximetazolina '],
            ['descripcion' => 'Xylometazolina clorhidrato'],
            ['descripcion' => 'Fenilefrina bitartrato o clorhidrato'],
            ['descripcion' => 'Salbutamol sulfato'],
            ['descripcion' => 'Acetaminofen '],
            ['descripcion' => 'Paracetamol'],
            ['descripcion' => 'Cafeína '],
            ['descripcion' => 'Ácido Mefenámico'],
            ['descripcion' => 'Ácido Acetilsalicílico'],
            ['descripcion' => 'Diclofenac sódico o potásico'],
            ['descripcion' => 'Metamizol '],
            ['descripcion' => 'Naproxeno '],
            ['descripcion' => 'Diclofenac sódico  '],
            ['descripcion' => 'Vitamina B1'],
            ['descripcion' => 'Vitamina B6 '],
            ['descripcion' => 'Vitamina B12.'],
            ['descripcion' => 'Fenazopiridina '],
            ['descripcion' => 'Salicilato de metilo '],
            ['descripcion' => 'Alcanfor '],
            ['descripcion' => 'Mentol '],
            ['descripcion' => 'Trementina'],
            ['descripcion' => 'Diclofenaco sódico o potásico'],
            ['descripcion' => 'Ketoprofeno sódico '],
            ['descripcion' => 'Bencidamina '],
            ['descripcion' => 'Piroxicam'],
            ['descripcion' => 'Cápsicos'],
            ['descripcion' => 'Cetilpiridinio'],
            ['descripcion' => 'Diclorobencílico'],
            ['descripcion' => 'Amilmetacresol'],
            ['descripcion' => 'Famotidina '],
            ['descripcion' => 'Ranitidina '],
            ['descripcion' => 'Simeticona '],
            ['descripcion' => 'Dimeticona'],
            ['descripcion' => 'Albendazol '],
            ['descripcion' => 'Furazolidona'],
            ['descripcion' => 'Mebendazol '],
            ['descripcion' => 'Loperamida'],
            ['descripcion' => 'Citrato trisódico dihidratado'],
            ['descripcion' => 'Glucosa anhidra'],
            ['descripcion' => 'Cloruro de Sodio'],
            ['descripcion' => 'Cloruro de Potasio'],
            ['descripcion' => 'Subsalicilato de bismuto'],
            ['descripcion' => 'Kaolin coloidal'],
            ['descripcion' => 'Aceite mineral.'],
            ['descripcion' => 'Carbonato de magnesio'],
            ['descripcion' => 'Ácido cítrico '],
            ['descripcion' => 'Fosfato de sodio'],
            ['descripcion' => 'Fosfato monobásico '],
            ['descripcion' => 'Fosfato dibásico '],
            ['descripcion' => 'Hidróxido de magnesio'],
            ['descripcion' => 'Dimenhidrinato '],
            ['descripcion' => 'Ácido glutámico '],
            ['descripcion' => 'Lecitina.'],
            ['descripcion' => 'Ácido Fólico '],
            ['descripcion' => 'Hierro '],
            ['descripcion' => 'Vitamina C.'],
            ['descripcion' => 'Jalea Real '],
            ['descripcion' => 'Extracto de Malta '],
            ['descripcion' => 'Bacitracina 0.5%. tópica'],
            ['descripcion' => 'Neomicina'],
            ['descripcion' => 'Clostebol'],
            ['descripcion' => 'Oxitetraciclina '],
            ['descripcion' => 'Polimixina'],
            ['descripcion' => 'Polimixina B sulfato '],
            ['descripcion' => 'Bacitracina de zinc'],
            ['descripcion' => 'Neomicina sulfato'],
            ['descripcion' => 'Vitamina A '],
            ['descripcion' => 'Pantenol '],
            ['descripcion' => 'Nistatina'],
            ['descripcion' => 'Butenafina '],
            ['descripcion' => 'Terbinafina '],
            ['descripcion' => 'Ácido Undecilénico'],
            ['descripcion' => 'Ácido Salicílico'],
            ['descripcion' => 'Clotrimazol '],
            ['descripcion' => 'Tolnaftato '],
            ['descripcion' => 'Aciclovir '],
            ['descripcion' => 'Azufre'],
            ['descripcion' => 'Peróxido de benzoilo '],
            ['descripcion' => 'Polidocanol'],
            ['descripcion' => 'Podofilina en alcohol '],
            ['descripcion' => 'Permetrina '],
            ['descripcion' => 'Benzoato de bencilo '],
            ['descripcion' => 'Deltametrina '],
            ['descripcion' => 'Pixide Enebro '],
            ['descripcion' => 'Alquitrán '],
            ['descripcion' => 'Dalibour '],
            ['descripcion' => 'Brea de hulla '],
            ['descripcion' => 'Ketoconazol '],
            ['descripcion' => 'Sulfuro de selenio  '],
            ['descripcion' => 'Piritionato de zinc'],
            ['descripcion' => 'Aceite de Hígado de tiburón '],
            ['descripcion' => 'Óxido de zinc'],
            ['descripcion' => 'Crotamiton '],
            ['descripcion' => 'Caolín '],
            ['descripcion' => 'Agua Hamamelis'],
            ['descripcion' => 'Calamina '],
            ['descripcion' => 'Glicerina '],
            ['descripcion' => 'Lanolina '],
            ['descripcion' => 'Aloe vera '],
            ['descripcion' => 'Jalea Tópica'],
            ['descripcion' => 'Talco '],
            ['descripcion' => 'Vaselina '],
            ['descripcion' => 'Vitamina D'],
            ['descripcion' => 'Aceite mineral '],
            ['descripcion' => 'Benzocaína '],
            ['descripcion' => 'Caproato de Prednisolona '],
            ['descripcion' => 'Sincocaína clorhidrato.'],
            ['descripcion' => 'Fenilefrina clorhidrato'],
            ['descripcion' => 'Tribenósido '],
            ['descripcion' => 'Lidocaína clorhidrato'],
            ['descripcion' => 'Metronidazol. '],
            ['descripcion' => 'Miconazol '],
            ['descripcion' => 'Alcohol '],
            ['descripcion' => 'Alcohol isopropílico '],
            ['descripcion' => 'Iodopovidona '],
            ['descripcion' => 'Cloruro de benzalconio '],
            ['descripcion' => 'Cetrimida '],
            ['descripcion' => 'Clorhexidina '],
            ['descripcion' => 'Sulfato de aluminio'],
            ['descripcion' => 'Acetato de calcio'],
            ['descripcion' => 'Acetato de aluminio'],
            ['descripcion' => 'Ácido poliacrílico '],
            ['descripcion' => 'Carboximetilcelulosa '],
            ['descripcion' => 'Hidroxipropilmetilcelulosa sódica'],
            ['descripcion' => 'Hialuronato de sodio'],
            ['descripcion' => 'Condroitín'],
            ['descripcion' => 'Fenilefrina'],
            ['descripcion' => 'Lágrimas artificiales'],
            ['descripcion' => 'Tetrahidrozolina'],
            ['descripcion' => 'clorhidrato'],
        ];
        foreach($datos as $conce){
            PrincipioActivo::create($conce);
        }
    }
}
